"""Deterministic assembly for feature-refinement documents."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .profiles import refine_template_path


class RefinementError(ValueError):
    """Raised when a model-produced strategy fragment is not safe to assemble."""


FEATURE_DOCUMENT_RENDERER = "core:rhai-feature-document-v1"
STRATEGY_HEADING = "Strategy (AI Generated by Agentic SDLC Pipeline)"
STAFF_HEADING = "Staff Engineer / SME Input"


def uses_feature_document_assembly(stage_definition: dict[str, Any]) -> bool:
    assembly = stage_definition.get("assembly")
    return isinstance(assembly, dict) and assembly.get("renderer") == FEATURE_DOCUMENT_RENDERER


def _headings(markdown: str) -> list[str]:
    return re.findall(r"^#{1,6}\s+(.+?)\s*$", markdown, flags=re.MULTILINE)


def _heading_matches(heading: str, required_name: str) -> bool:
    """Match a template heading while allowing a human-readable qualifier.

    Workers commonly retain the template section name and add a qualifier such
    as ``Acceptance Criteria (Proposed)``.  The section is still identifiable
    and safe to assemble; a word continuation such as ``Acceptance
    CriteriaDraft`` is not.
    """
    return heading == required_name or (
        heading.startswith(required_name)
        and len(heading) > len(required_name)
        and heading[len(required_name)] in " \t(:-\N{EN DASH}\N{EM DASH}"
    )


def validate_strategy_fragment(fragment: str) -> str:
    """Accept only the model-owned section of a feature document."""
    normalized = fragment.replace("\r\n", "\n").strip()
    if not normalized.startswith(f"## {STRATEGY_HEADING}"):
        raise RefinementError(f"strategy fragment must begin with '## {STRATEGY_HEADING}'")
    headings = _headings(normalized)
    forbidden = ("Business Need", STAFF_HEADING)
    found = [name for name in forbidden if any(_heading_matches(heading, name) for heading in headings)]
    if found:
        raise RefinementError("strategy fragment must not contain " + ", ".join(sorted(found)))
    required = ("TL;DR", "Technical Approach", "Acceptance Criteria")
    missing = [name for name in required if not any(_heading_matches(heading, name) for heading in headings)]
    if missing:
        raise RefinementError("strategy fragment is missing required headings: " + ", ".join(missing))
    return normalized


def _staff_section(install_root: Path, profile: dict[str, Any]) -> str:
    template = refine_template_path(install_root, profile).read_text(encoding="utf-8")
    marker = f"## {STAFF_HEADING}"
    _, separator, tail = template.partition(marker)
    if not separator or not tail.strip():
        raise RefinementError(f"feature template has no {marker} section")
    return marker + tail.rstrip()


def _source_text(source_issue: dict[str, Any]) -> tuple[str, str]:
    fields = source_issue.get("fields", {}) if isinstance(source_issue, dict) else {}
    summary = fields.get("summary") if isinstance(fields, dict) else None
    description = fields.get("description") if isinstance(fields, dict) else None
    if not isinstance(summary, str) or not summary.strip():
        raise RefinementError("captured feature source has no non-empty fields.summary")
    if not isinstance(description, str) or not description.strip():
        raise RefinementError("captured feature source has no non-empty fields.description")
    return summary.rstrip(), description.rstrip()


def assemble_feature_document(
    install_root: Path,
    profile: dict[str, Any],
    source_issue: dict[str, Any],
    fragment: str,
) -> str:
    """Combine immutable Jira source, validated model output, and template footer."""
    summary, description = _source_text(source_issue)
    strategy = validate_strategy_fragment(fragment)
    return (
        "## Business Need\n\n"
        f"**Summary**: {summary}\n\n"
        "**Description**:\n\n"
        f"{description}\n\n"
        "---\n\n"
        f"{strategy}\n\n"
        f"{_staff_section(install_root, profile)}\n"
    )
