import json
import shutil
from pathlib import Path

import pytest
import yaml

from adlc_workflow.core import WorkflowCore, WorkflowError
from adlc_workflow.artifacts import ArtifactLayout
from adlc_workflow.refinement import RefinementError, validate_strategy_fragment
from adlc_workflow.selection import SelectionError, normalize_request


def request(*keys: str) -> dict:
    return {
        "args": list(keys),
        "kwargs": {
            "mode": "eval",
            "identity": "test",
            "source_issue": {
                "key": keys[0] if keys else "RHAIRFE-1",
                "fields": {
                    "issuetype": {"name": "Feature Request"},
                    "labels": ["rfe-creator-autofix-rubric-pass", "strat-creator-3.6"],
                    "status": "Approved",
                    "customfield_10855": "3.6 GA RHOAI RELEASE",
                    "summary": f"{keys[0] if keys else 'RHAIRFE-1'} summary",
                    "description": f"{keys[0] if keys else 'RHAIRFE-1'} description",
                },
            },
        },
    }


def feature_fragment(approach: str) -> str:
    return (
        "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
        "### TL;DR\n\nA concise summary.\n\n"
        f"### Technical Approach\n\n{approach}\n\n"
        "### Acceptance Criteria\n\n- The feature is delivered.\n"
    )


def test_feature_fragment_allows_qualified_template_section_names() -> None:
    fragment = feature_fragment("A bounded approach.").replace(
        "### Acceptance Criteria\n", "### Acceptance Criteria (Proposed — requires validation)\n"
    )

    assert validate_strategy_fragment(fragment) == fragment.strip()


def test_feature_fragment_rejects_qualified_immutable_business_need_section() -> None:
    fragment = feature_fragment("A bounded approach.") + "\n## Business Need (copied source)\n"

    with pytest.raises(RefinementError, match="Business Need"):
        validate_strategy_fragment(fragment)


def complete_review_evidence(project: Path, issue_key: str) -> None:
    """Supply deterministic review outputs when this test submits a review directly."""
    profile = yaml.safe_load((project / "config/rhai-feature-creator.yaml").read_text())
    layout = ArtifactLayout(project, profile)
    for path in layout.reviewer_paths(issue_key).values():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("# Reviewer\n\nPass.\n", encoding="utf-8")
    score = layout.generated("score", issue_key)
    score.parent.mkdir(parents=True, exist_ok=True)
    score.write_text(json.dumps({"verdict": "approve", "total": 8}), encoding="utf-8")


@pytest.fixture
def project(tmp_path: Path) -> Path:
    source_root = Path(__file__).parents[2]
    for name in ("agents", "config", "context", "schemas", "skills", "templates"):
        shutil.copytree(source_root / name, tmp_path / name)
    profile_path = tmp_path / "config" / "rhai-feature-creator.yaml"
    profile = yaml.safe_load(profile_path.read_text())
    profile["context_sources"] = []
    profile_path.write_text(yaml.safe_dump(profile, sort_keys=False))
    return tmp_path


def test_request_normalization_deduplicates_keys() -> None:
    normalized = normalize_request(request("RHAIRFE-1", "RHAIRFE-1"), default_profile="profile.yaml")
    assert normalized.args == ("RHAIRFE-1",)
    assert normalized.selector == "keys"


def test_request_rejects_conflicting_selector() -> None:
    with pytest.raises(SelectionError, match="cannot be combined"):
        normalize_request(
            {"args": ["RHAIRFE-1"], "kwargs": {"mode": "eval", "jql_default": True}},
            default_profile="profile.yaml",
        )


def test_core_assigns_unique_ids_to_repeated_invocations(project: Path) -> None:
    core = WorkflowCore(project)

    first = core.start(request("RHAIRFE-1"))
    second = core.start(request("RHAIRFE-1"))

    assert first["run_id"] != second["run_id"]
    assert first["items"][0]["work_id"] != second["items"][0]["work_id"]
    assert (project / ".adlc" / "state" / "runs" / first["run_id"] / "state.json").is_file()
    assert (project / ".adlc" / "state" / "runs" / second["run_id"] / "state.json").is_file()


def test_core_emits_refine_and_review_tasks(project: Path) -> None:
    core = WorkflowCore(project)
    started = core.start(request("RHAIRFE-1"))
    run_id = started["run_id"]

    refine = core.advance(run_id)
    assert refine["kind"] == "task"
    assert refine["stage"] == "refine"
    assert Path(refine["fragment_path"]).is_relative_to(project / ".adlc" / "state")
    assert refine["worker_resources"]["source_request_path"].endswith("request.json")
    assert refine["worker_resources"]["template_path"].endswith("templates/rhai-feature-creator/feature-template.md")
    assert refine["worker_resources"]["context_manifest_path"] == str(project / ".context/context-manifest.json")
    assert isinstance(refine["worker_resources"]["overlay_paths"], list)
    assert not (project / "artifacts/rhai-feature-tasks/RHAIRFE-1.md").exists()
    refine_result = {
        "task_id": refine["task_id"],
        "run_id": run_id,
        "revision": refine["expected_revision"],
        "outputs": {"strategy_markdown": feature_fragment("A bounded approach.")},
    }
    core.submit(run_id, refine["task_id"], refine_result)

    review = core.advance(run_id)
    assert review["stage"] == "review"
    review_result = {
        "task_id": review["task_id"],
        "run_id": run_id,
        "revision": review["expected_revision"],
        "outputs": {"review_markdown": "# Review\n\nNeeds validation."},
    }
    core.submit(run_id, review["task_id"], review_result)
    complete_review_evidence(project, "RHAIRFE-1")
    feature = (project / "artifacts" / "rhai-feature-tasks" / "RHAIRFE-1.md").read_text()
    assert "**Summary**: RHAIRFE-1 summary" in feature
    assert "RHAIRFE-1 description" in feature
    assert "A bounded approach." in feature
    assert "## Staff Engineer / SME Input" in feature
    assert (project / "artifacts" / "rhai-feature-reviews" / "RHAIRFE-1-review.md").read_text() == "# Review\n\nNeeds validation."
    complete = core.advance(run_id)
    assert complete["kind"] == "complete"
    assert complete["publication"]["status"] == "complete"
    assert (project / "artifacts" / "rhai-feature-published" / run_id / "manifest.json").is_file()


def test_core_rejects_a_fragment_that_attempts_to_replace_business_need(project: Path) -> None:
    core = WorkflowCore(project)
    run_id = core.start(request("RHAIRFE-1"))["run_id"]
    refine = core.advance(run_id)
    malicious = feature_fragment("A bounded approach.") + "\n## Business Need\n\nAltered source.\n"
    with pytest.raises(WorkflowError, match="must not contain Business Need"):
        core.submit(run_id, refine["task_id"], {
            "task_id": refine["task_id"],
            "run_id": run_id,
            "revision": refine["expected_revision"],
            "outputs": {"strategy_markdown": malicious},
        })


def test_core_preserves_per_issue_gate_context_for_batch(project: Path) -> None:
    document = request("RHAIRFE-10", "RHAIRFE-11")
    document["kwargs"]["source_issues"] = {
        key: {"key": key, "fields": {
            "issuetype": {"name": "Feature Request"},
            "labels": ["rfe-creator-rubric-pass"],
            "status": "New",
            "customfield_10855": "3.6 GA RHOAI RELEASE",
        }}
        for key in ("RHAIRFE-10", "RHAIRFE-11")
    }
    document["kwargs"].pop("source_issue")
    core = WorkflowCore(project)
    started = core.start(document)
    state = core.status(started["run_id"])
    assert set(state["gate_context"]["sources"]) == {"RHAIRFE-10", "RHAIRFE-11"}
    first = core.advance(started["run_id"])
    assert first["issue_key"] == "RHAIRFE-10"


def test_core_completes_all_batch_items_before_publication(project: Path) -> None:
    core = WorkflowCore(project)
    started = core.start(request("RHAIRFE-10", "RHAIRFE-11"))
    run_id = started["run_id"]

    for issue_key in ("RHAIRFE-10", "RHAIRFE-11"):
        refine = core.advance(run_id)
        assert refine["issue_key"] == issue_key
        core.submit(run_id, refine["task_id"], {
            "task_id": refine["task_id"],
            "run_id": run_id,
            "revision": refine["expected_revision"],
            "outputs": {"strategy_markdown": feature_fragment(f"Approach for {issue_key}.")},
        })
        review = core.advance(run_id)
        assert review["issue_key"] == issue_key
        core.submit(run_id, review["task_id"], {
            "task_id": review["task_id"],
            "run_id": run_id,
            "revision": review["expected_revision"],
            "outputs": {"review_markdown": f"# Review {issue_key}"},
        })
        complete_review_evidence(project, issue_key)

    complete = core.advance(run_id)
    assert complete["kind"] == "complete"
    assert complete["publication"]["status"] == "complete"


def test_core_uses_profile_selected_artifact_roots(project: Path) -> None:
    profile_path = project / "config" / "rhai-feature-creator.yaml"
    profile = yaml.safe_load(profile_path.read_text())
    profile["artifacts"]["bundle_root"] = "bundle"
    profile["artifacts"]["roots"] = {
        "tasks": "bundle/feature-docs",
        "originals": "bundle/source",
        "reviews": "bundle/assessments",
        "inputs": "bundle/context",
        "extensions": "bundle/extensions",
        "reports": "bundle/reports",
        "published": "bundle/published",
    }
    profile["artifacts"]["evidence_files"] = {
        "selection": "selection.json",
        "pipeline_data": "pipeline-data.json",
    }
    profile_path.write_text(yaml.safe_dump(profile, sort_keys=False))

    core = WorkflowCore(project)
    started = core.start(request("RHAIRFE-5"))

    assert (project / "bundle" / "selection.json").is_file()
    assert not (project / "artifacts" / "selection.json").exists()
    assert (project / "bundle" / "context" / "context-manifest.json").is_file()
    assert started["selection_path"] == "bundle/selection.json"


def test_core_rejects_stale_result(project: Path) -> None:
    core = WorkflowCore(project)
    run_id = core.start(request("RHAIRFE-2"))["run_id"]
    task = core.advance(run_id)
    bad_result = {
        "task_id": task["task_id"],
        "run_id": run_id,
        "revision": 99,
        "outputs": {"strategy_markdown": feature_fragment("A stale result.")},
    }
    with pytest.raises(WorkflowError, match="revision"):
        core.submit(run_id, task["task_id"], bad_result)


def test_empty_selection_is_explicit_noop(project: Path) -> None:
    core = WorkflowCore(project)
    started = core.start({"args": [], "kwargs": {"mode": "eval"}})
    assert started["status"] == "complete"
    assert started["items"] == []
    selection = json.loads((project / "artifacts" / "rhai-feature-selection.json").read_text())
    assert selection["selection_status"] == "empty"


def test_install_and_workspace_roots_are_separate(project: Path, tmp_path: Path) -> None:
    workspace = tmp_path / "runtime"
    core = WorkflowCore(project, workspace)
    core.start(request("RHAIRFE-3"))
    assert (workspace / "artifacts" / "rhai-feature-selection.json").is_file()
    assert not (project / "artifacts" / "rhai-feature-selection.json").exists()


def test_linked_install_root_accepts_symlinked_profile(project: Path, tmp_path: Path) -> None:
    linked = tmp_path / "cache" / "adlc-workflow"
    linked.parent.mkdir()
    linked.symlink_to(project, target_is_directory=True)

    core = WorkflowCore(linked, tmp_path / "runtime")
    started = core.start(request("RHAIRFE-4"))

    assert started["status"] == "running"
