"""Standard-library coverage for deterministic handoff orchestration."""

from __future__ import annotations

import json
import re
import shutil
import io
import tempfile
import threading
import time
import unittest
from contextlib import redirect_stdout
from pathlib import Path

import yaml

from adlc_workflow.controller import ControllerError, ControllerOptions, HandoffController, _usage_summary
from adlc_workflow.profiles import ProfileError, resolve_profile_path


SOURCE = Path(__file__).parents[2]


def issue(key: str, *, status: str = "Approved") -> dict:
    return {
        "key": key,
        "fields": {
            "project": {"key": "RHAIRFE"},
            "issuetype": {"name": "Feature Request"},
            "labels": ["rfe-creator-rubric-pass", "strat-creator-3.6"],
            "status": {"name": status},
            "customfield_10855": "3.6 GA RHOAI RELEASE",
            "summary": f"Feature {key}",
            "description": "A bounded feature request.",
            "issuelinks": [],
        },
    }


class FakeJira:
    def __init__(self, issues: dict[str, dict]):
        self.issues = issues
        self.searches: list[tuple[str, int, int]] = []

    def issue(self, key: str) -> dict:
        return self.issues[key]

    def search(self, jql: str, *, start_at: int, max_results: int) -> dict:
        self.searches.append((jql, start_at, max_results))
        values = [{"key": key} for key in self.issues]
        return {"issues": values[start_at:start_at + max_results], "total": len(values)}


class FakeWorkers:
    def __init__(self, *, reviewer_delay: float = 0, refine_delay: float = 0):
        self.calls: list[str] = []
        self.reviewer_delay = reviewer_delay
        self.refine_delay = refine_delay
        self._active_reviewers = 0
        self.max_active_reviewers = 0
        self._active_refinements = 0
        self.max_active_refinements = 0
        self._lock = threading.Lock()

    def run(self, *, worker_name: str, prompt: str, attempt_dir: Path,
            event_context: dict) -> str:
        self.calls.append(worker_name)
        attempt_dir.mkdir(parents=True, exist_ok=True)
        is_reviewer = "reviewer" in worker_name
        is_refinement = worker_name == "rhai-feature-refine-worker"
        if is_reviewer:
            with self._lock:
                self._active_reviewers += 1
                self.max_active_reviewers = max(self.max_active_reviewers, self._active_reviewers)
            time.sleep(self.reviewer_delay)
        if is_refinement:
            with self._lock:
                self._active_refinements += 1
                self.max_active_refinements = max(self.max_active_refinements, self._active_refinements)
            time.sleep(self.refine_delay)
        required = re.search(r"Required output paths: (\{.*\})", prompt)
        try:
            if required:
                paths = json.loads(required.group(1))
                for name, path in paths.items():
                    destination = Path(path)
                    destination.parent.mkdir(parents=True, exist_ok=True)
                    destination.write_text(f"# {name}\n\nGenerated by {worker_name}.\n", encoding="utf-8")
                issue_key = re.search(r'"issue_key": "([^"]+)"', prompt).group(1)
                return json.dumps({"status": "written", "issue_key": issue_key, "artifact_path": next(iter(paths.values()))})
            output = re.search(r'"output_path": "([^"]+)"', prompt)
            if output is None:
                raise AssertionError(f"worker prompt did not name an output path: {prompt}")
            destination = Path(output.group(1))
            destination.parent.mkdir(parents=True, exist_ok=True)
            if "scoring" in worker_name:
                content = "# Scoring review\n\nVerdict: PASS (score: 8/8)\n"
            else:
                content = f"# {worker_name}\n\nIndependent finding.\n"
            destination.write_text(content, encoding="utf-8")
            return str(destination)
        finally:
            if is_reviewer:
                with self._lock:
                    self._active_reviewers -= 1
            if is_refinement:
                with self._lock:
                    self._active_refinements -= 1


class NoopWorkers:
    def run(self, *, worker_name: str, prompt: str, attempt_dir: Path,
            event_context: dict) -> str:
        attempt_dir.mkdir(parents=True, exist_ok=True)
        issue_key = re.search(r'"issue_key": "([^"]+)"', prompt).group(1)
        return json.dumps({"status": "written", "issue_key": issue_key, "artifact_path": "/missing.md"})


class ControllerTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        self.install = self.root / "install"
        for name in ("config", "skills", "agents", "templates", "schemas", ".claude-plugin"):
            shutil.copytree(SOURCE / name, self.install / name)
        profile_path = self.install / "config/rhai-feature-creator.yaml"
        profile = yaml.safe_load(profile_path.read_text(encoding="utf-8"))
        profile["context_sources"] = []
        profile["controller"] = {"reviewer_parallelism": 3, "task_timeout_seconds": 30}
        profile_path.write_text(yaml.safe_dump(profile, sort_keys=False), encoding="utf-8")
        self.workspace = self.root / "workspace"

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def test_profile_name_resolution(self) -> None:
        self.assertEqual(
            resolve_profile_path(self.install, "rhai-feature-creator"),
            "config/rhai-feature-creator.yaml",
        )
        self.assertEqual(
            resolve_profile_path(self.install, "config/rhai-feature-creator.yaml"),
            "config/rhai-feature-creator.yaml",
        )
        with self.assertRaises(ProfileError):
            resolve_profile_path(self.install, "../outside")

    def test_explicit_key_handoff_completes_with_shared_core_protocol(self) -> None:
        jira = FakeJira({"RHAIRFE-1": issue("RHAIRFE-1")})
        workers = FakeWorkers()
        controller = HandoffController(
            self.install,
            self.workspace,
            ControllerOptions(profile="rhai-feature-creator", issue_keys=("RHAIRFE-1",), mode="eval"),
            jira=jira,
            workers=workers,
        )

        result = controller.run()

        self.assertEqual(result["kind"], "complete")
        self.assertGreaterEqual(result["duration_seconds"], 0)
        self.assertEqual(workers.calls.count("rhai-feature-refine-worker"), 1)
        self.assertEqual(len([name for name in workers.calls if "reviewer" in name]), 5)
        self.assertTrue((self.workspace / "artifacts/rhai-feature-tasks/RHAIRFE-1.md").is_file())
        self.assertTrue((self.workspace / "artifacts/rhai-feature-reviews/RHAIRFE-1-review.md").is_file())
        score = json.loads((self.workspace / "artifacts/rhai-feature-reviews/RHAIRFE-1-score.json").read_text(encoding="utf-8"))
        self.assertEqual(score["verdict"], "approve")
        self.assertTrue((self.workspace / "artifacts/rhai-feature-published" / result["run_id"] / "manifest.json").is_file())

    def test_parallel_reviewers_honor_profile_cap(self) -> None:
        workers = FakeWorkers(reviewer_delay=0.03)
        controller = HandoffController(
            self.install,
            self.workspace,
            ControllerOptions(profile="rhai-feature-creator", issue_keys=("RHAIRFE-1",), mode="eval"),
            jira=FakeJira({"RHAIRFE-1": issue("RHAIRFE-1")} ),
            workers=workers,
        )

        controller.run()

        self.assertEqual(workers.max_active_reviewers, 3)

    def test_item_parallelism_claims_distinct_batch_tasks(self) -> None:
        workers = FakeWorkers(refine_delay=0.03)
        controller = HandoffController(
            self.install,
            self.workspace,
            ControllerOptions(
                profile="rhai-feature-creator",
                issue_keys=("RHAIRFE-1", "RHAIRFE-2"),
                mode="eval",
                item_parallelism=2,
            ),
            jira=FakeJira({"RHAIRFE-1": issue("RHAIRFE-1"), "RHAIRFE-2": issue("RHAIRFE-2")} ),
            workers=workers,
        )

        result = controller.run()

        self.assertEqual(result["kind"], "complete")
        self.assertEqual(workers.max_active_refinements, 2)
        self.assertEqual(workers.calls.count("rhai-feature-refine-worker"), 2)

    def test_second_controller_is_rejected_while_workspace_lease_is_held(self) -> None:
        controller = HandoffController(
            self.install,
            self.workspace,
            ControllerOptions(profile="rhai-feature-creator", issue_keys=("RHAIRFE-1",), mode="eval"),
            jira=FakeJira({"RHAIRFE-1": issue("RHAIRFE-1")} ),
            workers=FakeWorkers(),
        )

        with controller.core.state.execution_lease():
            with self.assertRaises(ControllerError):
                controller.run()

    def test_json_output_is_a_private_and_public_jsonl_event_stream(self) -> None:
        controller = HandoffController(
            self.install,
            self.workspace,
            ControllerOptions(profile="rhai-feature-creator", issue_keys=("RHAIRFE-1",), mode="eval", output="json"),
            jira=FakeJira({"RHAIRFE-1": issue("RHAIRFE-1")} ),
            workers=FakeWorkers(),
        )
        captured = io.StringIO()
        with redirect_stdout(captured):
            result = controller.run()

        events = [json.loads(line) for line in captured.getvalue().splitlines()]
        self.assertEqual(events[-1]["type"], "controller.run_finished")
        self.assertEqual(events[-1]["result"]["run_id"], result["run_id"])
        review_event = next(event for event in events if event["type"] == "controller.review_verdict")
        self.assertEqual(review_event["review"]["verdict"], "approve")
        private_events = self.workspace / ".adlc/state/runs" / result["run_id"] / "events.jsonl"
        self.assertTrue(private_events.is_file())
        self.assertIn('"type":"controller.task_started"', private_events.read_text(encoding="utf-8"))

    def test_usage_summary_aggregates_terminal_worker_events(self) -> None:
        event_path = self.root / "events.jsonl"
        event_path.write_text("\n".join([
            json.dumps({"type": "claude.stream", "event": {
                "type": "result", "is_error": False, "modelUsage": {
                    "claude-haiku-4-5": {
                        "costUSD": 0.125, "inputTokens": 3, "outputTokens": 5,
                        "cacheReadInputTokens": 7, "cacheCreationInputTokens": 11,
                        "thinkingTokens": 13,
                    },
                },
            }}),
            json.dumps({"type": "claude.stream", "event": {
                "type": "result", "is_error": True, "modelUsage": {"ignored": {"costUSD": 99}},
            }}),
        ]) + "\n", encoding="utf-8")

        summary = _usage_summary(event_path)

        self.assertEqual(summary["workers"], 1)
        self.assertEqual(summary["cost_usd"], 0.125)
        self.assertEqual(summary["cache_read_input_tokens"], 7)
        self.assertEqual(summary["models"]["claude-haiku-4-5"]["thinking_tokens"], 13)

    def test_profile_only_selection_filters_and_freezes_candidates(self) -> None:
        jira = FakeJira({
            "RHAIRFE-2": issue("RHAIRFE-2"),
            "RHAIRFE-1": issue("RHAIRFE-1"),
            "RHAIRFE-3": issue("RHAIRFE-3", status="Closed"),
        })
        controller = HandoffController(
            self.install,
            self.workspace,
            ControllerOptions(profile="rhai-feature-creator", mode="eval", batch_size=1),
            jira=jira,
            workers=FakeWorkers(),
        )

        selection = controller._select()

        self.assertEqual(selection["keys"], ["RHAIRFE-1"])
        self.assertEqual(selection["evidence"]["selector"], "profile-gate")
        self.assertIn("RHAIRFE-3", selection["evidence"]["exclusion_reasons"])
        self.assertIn('project = "RHAIRFE"', jira.searches[0][0])

    def test_stale_task_artifact_is_not_accepted_as_worker_output(self) -> None:
        stale = self.workspace / "artifacts/rhai-feature-tasks/RHAIRFE-1.md"
        stale.parent.mkdir(parents=True, exist_ok=True)
        stale.write_text("# stale\n", encoding="utf-8")
        controller = HandoffController(
            self.install,
            self.workspace,
            ControllerOptions(profile="rhai-feature-creator", issue_keys=("RHAIRFE-1",), mode="eval"),
            jira=FakeJira({"RHAIRFE-1": issue("RHAIRFE-1")} ),
            workers=NoopWorkers(),
        )

        with self.assertRaises(ControllerError, msg="a stale artifact must not satisfy a new task"):
            controller.run()

        self.assertFalse(stale.exists())


if __name__ == "__main__":
    unittest.main()
